### ISSUE TITLE
LeoCAD crashed with Mesa 17.2.4 (if antialising was enabled)

### ISSUE THREAD

**Issue by Symbian9** [leozide/leocad#134]
OS: Linux Mint 18.2 Xfce (x86_64), upgraded on 2017/Oct/12
GPU: ATI RS600
OpenGL driver: Mesa 17.2.4

```
mint@mint-SR58P ~/AppImages $ gdb ./LeoCAD-git.6ca7934.qt57-x86_64.AppImage
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./LeoCAD-git.6ca7934.qt57-x86_64.AppImage...(no debugging symbols found)...done.
(gdb) r
Starting program: /home/mint/AppImages/LeoCAD-git.6ca7934.qt57-x86_64.AppImage 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
process 14038 is executing new program: /tmp/.mount_LeoCAD6GXpZp/usr/bin/leocad
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffed6f4700 (LWP 14047)]
[New Thread 0x7fffe7fff700 (LWP 14048)]
[New Thread 0x7fffe58dc700 (LWP 14049)]
[New Thread 0x7fffdc045700 (LWP 14050)]

Thread 1 "AppRun" received signal SIGSEGV, Segmentation fault.
0x00007fffec41e321 in ?? ()
(gdb) bt
#0  0x00007fffec41e321 in ?? ()
#1  0x00000000016b71e0 in ?? ()
#2  0x0000000001beb3f0 in ?? ()
#3  0x0000000000000000 in ?? ()
(gdb) 
```

**Comment by Symbian9** [comment]
@leozide, Its look like LeoCAD crashed if antialising enabled, if dissable antialising then its possible to use LeoCAD withu Mesa 17.2.4

P.S.: Previously I has Mesa 12.0.6 and there was no such bug.

**Comment by leozide** [comment]
I'll try to repro, but a backtrace with symbols would help.

**Comment by Symbian9** [comment]
> backtrace with symbols would help.

What should I do for it?

**Comment by leozide** [comment]
Compile the binary locally and run

**Comment by Symbian9** [comment]
Duplicate of https://github.com/leozide/leocad/issues/95
