### ISSUE TITLE
Another segfault when reloading model

### ISSUE THREAD

**Issue by ali1234** [leozide/leocad#277]
This one is not so easily reproducible. It happens every time I touch the model file and say "yes" to the reload dialog. However, if I move or rename the model file first then it does not happen, so I assume that the problem is related to the preferences file somehow.

Here is a backtrace:

```
Thread 1 "leocad" received signal SIGSEGV, Segmentation fault.
0x000055555563e85f in lcModel::GetMoveRotateTransform (this=0x555556915e20, Center=..., RelativeRotation=...)
    at common/lc_model.cpp:3018
3018			lcCamera* Camera = mCameras[CameraIdx];
(gdb) bt
#0  0x000055555563e85f in lcModel::GetMoveRotateTransform(lcVector3&, lcMatrix33&) const (this=0x555556915e20, Center=..., RelativeRotation=...) at common/lc_model.cpp:3018
#1  0x0000555555596a2c in View::GetOverlayScale() const (this=0x555557612d90) at common/view.cpp:1892
#2  0x0000555555596e89 in View::UpdateTrackTool() (this=0x555557612d90) at common/view.cpp:2002
#3  0x0000555555599f80 in View::OnMouseMove() (this=0x555557612d90) at common/view.cpp:2907
#4  0x00005555556b8e5c in lcQGLWidget::mouseMoveEvent(QMouseEvent*) (this=0x5555574b9e90, event=0x7fffffffbcb0)
    at qt/lc_qglwidget.cpp:303
#5  0x00007ffff703e038 in QWidget::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#6  0x00007ffff6fff82c in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#7  0x00007ffff700764f in QApplication::notify(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#8  0x00007ffff5ab29a8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#9  0x00007ffff7006622 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#10 0x00007ffff7006d90 in QApplicationPrivate::sendSyntheticEnterLeave(QWidget*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#11 0x00007ffff703dbf1 in QWidget::setVisible(bool) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#12 0x00007ffff7021fb0 in QStackedLayout::setCurrentIndex(int) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#13 0x00007ffff7022862 in QStackedLayout::takeAt(int) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#14 0x00007ffff701af20 in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#15 0x00007ffff6fff7fa in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#16 0x00007ffff70070f4 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#17 0x00007ffff5ab29a8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#18 0x00007ffff5ae8388 in QObjectPrivate::setParent_helper(QObject*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#19 0x00007ffff5ae89ff in QObject::~QObject() () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#20 0x00007ffff7039dd6 in QWidget::~QWidget() () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#21 0x00005555556d1fea in lcModelTabWidget::~lcModelTabWidget() (this=0x555557816850, __in_chrg=<optimised out>)
    at build/debug/.moc/../../../common/lc_mainwindow.h:46
#22 0x00005555556d200c in lcModelTabWidget::~lcModelTabWidget() (this=0x555557816850, __in_chrg=<optimised out>)
    at build/debug/.moc/../../../common/lc_mainwindow.h:46
#23 0x0000555555620f05 in lcMainWindow::RemoveAllModelTabs() (this=0x555555af91e0) at common/lc_mainwindow.cpp:1399
#24 0x00005555555e43ed in lcApplication::SetProject(Project*) (this=0x7fffffffddb0, Project=0x555555c6cb00)
    at common/lc_application.cpp:109
#25 0x000055555561ee24 in lcMainWindow::ProjectFileChanged(QString const&) (this=0x555555af91e0, Path=...)
    at common/lc_mainwindow.cpp:927
#26 0x00005555556d1d68 in lcMainWindow::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) (_o=0x555555af91e0, _c=QMetaObject::InvokeMetaMethod, _id=0, _a=0x7fffffffc4d0) at build/debug/.moc/moc_lc_mainwindow.cpp:179
#27 0x00007ffff5ae15b5 in QMetaObject::activate(QObject*, int, int, void**) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#28 0x00007ffff5a1ed8c in QFileSystemWatcher::fileChanged(QString const&, QFileSystemWatcher::QPrivateSignal) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#29 0x00007ffff5a1f545 in  () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#30 0x00007ffff5ae15b5 in QMetaObject::activate(QObject*, int, int, void**) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#31 0x00007ffff5a1ee53 in  () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#32 0x00007ffff5a4c721 in  () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#33 0x00007ffff5ae15b5 in QMetaObject::activate(QObject*, int, int, void**) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#34 0x00007ffff5aeda38 in QSocketNotifier::activated(int, QSocketNotifier::QPrivateSignal) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#35 0x00007ffff5aede02 in QSocketNotifier::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#36 0x00007ffff6fff82c in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#37 0x00007ffff70070f4 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#38 0x00007ffff5ab29a8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#39 0x00007ffff5b0c54d in  () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#40 0x00007ffff3246287 in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#41 0x00007ffff32464c0 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#42 0x00007ffff324654c in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#43 0x00007ffff5b0b8ef in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#44 0x00007ffff5ab09ea in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#45 0x00007ffff5ab9a84 in QCoreApplication::exec() () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#46 0x000055555566ca51 in main(int, char**) (argc=3, argv=0x7fffffffdf08) at qt/qtmain.cpp:169
```

**Comment by ali1234** [comment]
PS I did pull your previous fix.

**Comment by ali1234** [comment]
Also I just tried deleting LeoCAD.conf and that fixed the problem. Let me know if you need that file and the model.

**Comment by leozide** [comment]
I can't repro just touching a model file, can you post the bad files?

**Comment by ali1234** [comment]
[things.tar.gz](https://github.com/leozide/leocad/files/2550564/things.tar.gz)

You will need to copy the model to /home/al/Source/pirover/bricks/custom-parts/ (you should see this path in LeoCAD.conf)

**Comment by leozide** [comment]
It took me several tries to get the crash so I'm not 100% sure it's fixed.

**Comment by ali1234** [comment]
It was 100% reproducible for me but this patch fixed it. Thanks.

I'm hitting these reload bugs because I'm exporting the custom parts from Blender and merging them into the model file automatically with a Makefile. So every time I run that I get the "reload" message.

A suggestion: perhaps the dialog should not pop up until the next time Leocad has focus, rather than raising itself automatically. This is what most text editors and IDEs seem to do.
