### ISSUE TITLE
BUG: Move to step ahead freezes

### ISSUE THREAD

**Issue by hfiguiere** [leozide/leocad#614]
**Describe the bug**
In properties, when changing the "Visible steps > Show" property to a step head (ie a high number) freezes. Happens with 21.01 and `master`

**To Reproduce**
1. In a new model add one brick
2. Add another brick
3. Go to properties and edit "Visible Steps > Show"
4. Set it to 2
5. Leocad freezes

**Expected behavior**
The part is moved to step 2. If the step doesn't exist it is created.

**Screenshots**

**Version (please complete the following information):**
 - OS: Fedora 33
 - LeoCAD Version Flatpak 21.01 or self compiler from commit 7931720

**Crash information:**
gdb stack trace
```
#0  0x00007ffff7c50a86 in QVector<QTreeWidgetItem*>::~QVector() () at /lib64/libQt5Widgets.so.5
#1  0x00007ffff7c4adc6 in QTreeWidgetItemPrivate::updateHiddenStatus(QTreeWidgetItem*, bool) () at /lib64/libQt5Widgets.so.5
#2  0x00007ffff7c4b15f in QTreeWidgetItem::insertChild(int, QTreeWidgetItem*) () at /lib64/libQt5Widgets.so.5
#3  0x00007ffff7c4b387 in QTreeWidgetItem::addChild(QTreeWidgetItem*) () at /lib64/libQt5Widgets.so.5
#4  0x00000000004e2c24 in lcTimelineWidget::Update(bool, bool) (this=<optimized out>, Clear=<optimized out>, UpdateItems=false) at common/lc_timelinewidget.cpp:150
#5  0x0000000000491763 in lcMainWindow::UpdateTimeline(bool, bool) (this=<optimized out>, Clear=<optimized out>, UpdateItems=<optimized out>) at common/lc_mainwindow.cpp:2094
#6  0x00000000004bcaa9 in lcModel::SetSelectedPiecesStepShow(unsigned int) (this=this@entry=0xe3d5e0, Step=Step@entry=2) at common/lc_model.cpp:2887
#7  0x0000000000521bcb in lcQPropertiesTree::slotReturnPressed() (this=0xd95120) at qt/lc_qpropertiestree.cpp:640
#8  0x00007ffff6d1a3c0 in void doActivate<false>(QObject*, int, void**) () at /lib64/libQt5Core.so.5
#9  0x00007ffff6d1a3c0 in void doActivate<false>(QObject*, int, void**) () at /lib64/libQt5Core.so.5
#10 0x00007ffff7ab57eb in QWidgetLineControl::processKeyEvent(QKeyEvent*) () at /lib64/libQt5Widgets.so.5
#11 0x00007ffff7aa989f in QLineEdit::keyPressEvent(QKeyEvent*) () at /lib64/libQt5Widgets.so.5
#12 0x00007ffff79a997f in QWidget::event(QEvent*) () at /lib64/libQt5Widgets.so.5
#13 0x00007ffff7967ec3 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib64/libQt5Widgets.so.5
#14 0x00007ffff796f40f in QApplication::notify(QObject*, QEvent*) () at /lib64/libQt5Widgets.so.5
#15 0x00007ffff6ceabd8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib64/libQt5Core.so.5
#16 0x00007ffff79c4718 in QWidgetWindow::event(QEvent*) () at /lib64/libQt5Widgets.so.5
#17 0x00007ffff7967ec3 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib64/libQt5Widgets.so.5
#18 0x00007ffff6ceabd8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib64/libQt5Core.so.5
#19 0x00007ffff730a93a in QGuiApplicationPrivate::processKeyEvent(QWindowSystemInterfacePrivate::KeyEvent*) () at /lib64/libQt5Gui.so.5
#20 0x00007fffe402473c in QIBusPlatformInputContext::filterEventFinished(QDBusPendingCallWatcher*) ()
    at /usr/lib64/qt5/plugins/platforminputcontexts/libibusplatforminputcontextplugin.so
#21 0x00007ffff6d1a386 in void doActivate<false>(QObject*, int, void**) () at /lib64/libQt5Core.so.5
#22 0x00007fffe5d9d383 in QDBusPendingCallWatcher::finished(QDBusPendingCallWatcher*) () at /lib64/libQt5DBus.so.5
#23 0x00007ffff6d12d1e in QObject::event(QEvent*) () at /lib64/libQt5Core.so.5
#24 0x00007ffff7967ec3 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib64/libQt5Widgets.so.5
#25 0x00007ffff6ceabd8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib64/libQt5Core.so.5
#26 0x00007ffff6ced8c7 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /lib64/libQt5Core.so.5
#27 0x00007ffff6d37c27 in postEventSourceDispatch(_GSource*, int (*)(void*), void*) () at /lib64/libQt5Core.so.5
#28 0x00007ffff589e96f in g_main_context_dispatch () at /lib64/libglib-2.0.so.0
#29 0x00007ffff58f0758 in g_main_context_iterate.constprop () at /lib64/libglib-2.0.so.0
#30 0x00007ffff589bd43 in g_main_context_iteration () at /lib64/libglib-2.0.so.0
```

**Additional context**
Happens every time. I lost several edits because of that.

**Comment by hfiguiere** [comment]
Works great! Thanks !
