### ISSUE TITLE
Crash (working on the repro steps)

### ISSUE THREAD

**Issue by hfiguiere** [leozide/leocad#659]
**Describe the bug**
Leocad 21.03 (or master) is crashing, I don't have clear repro steps yet.

This one happen while looking for piece 24307 in the parts inventory

**To Reproduce**
TBD

**Expected behavior**

**Screenshots**

**Version (please complete the following information):**
 - OS: Fedora 33
 - LeoCAD Version 21.03 or master

**Crash information:**
```
=================================================================
==1017727==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x7f8a698039e0 at pc 0x0000006412b2 bp 0x7f8a79c57930 sp 0x7f8a79c57928
WRITE of size 4 at 0x7f8a698039e0 thread T30 (Thread (pooled))
    #0 0x6412b1 in lcLibraryMeshData::CreateMesh() common/lc_meshloader.cpp:1246
    #1 0x5b583d in lcPiecesLibrary::LoadPieceData(PieceInfo*) common/lc_library.cpp:1284
    #2 0x4a8227 in PieceInfo::Load() common/pieceinf.cpp:154
    #3 0x59ba74 in lcPiecesLibrary::LoadQueuedPiece() common/lc_library.cpp:1227
    #4 0x5bde97 in non-virtual thunk to QtConcurrent::RunFunctionTask<void>::run() (/home/hub/source/leocad/build/release/leocad+0x5bde97)
    #5 0x7f8a9c3d6f99  (/lib64/libQt5Core.so.5+0xe9f99)
    #6 0x7f8a9c3d3def  (/lib64/libQt5Core.so.5+0xe6def)
    #7 0x7f8a9c24d3f8 in start_thread (/lib64/libpthread.so.0+0x93f8)
    #8 0x7f8a9be2fb52 in __GI___clone (/lib64/libc.so.6+0x101b52)

0x7f8a698039e0 is located 0 bytes to the right of 4207072-byte region [0x7f8a69400800,0x7f8a698039e0)
allocated by thread T30 (Thread (pooled)) here:
    #0 0x7f8a9d8c43cf in __interceptor_malloc (/lib64/libasan.so.6+0xab3cf)
    #1 0x6028b9 in lcMesh::Create(unsigned short (&) [2], int, int, int, int) common/lc_mesh.cpp:68

Thread T30 (Thread (pooled)) created by T0 here:
    #0 0x7f8a9d86ef46 in __interceptor_pthread_create (/lib64/libasan.so.6+0x55f46)
    #1 0x7f8a9c3d38b9 in QThread::start(QThread::Priority) (/lib64/libQt5Core.so.5+0xe68b9)

SUMMARY: AddressSanitizer: heap-buffer-overflow common/lc_meshloader.cpp:1246 in lcLibraryMeshData::CreateMesh()
Shadow bytes around the buggy address:
  0x0ff1cd2f86e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ff1cd2f86f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ff1cd2f8700: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ff1cd2f8710: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ff1cd2f8720: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0ff1cd2f8730: 00 00 00 00 00 00 00 00 00 00 00 00[fa]fa fa fa
  0x0ff1cd2f8740: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0ff1cd2f8750: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0ff1cd2f8760: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0ff1cd2f8770: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0ff1cd2f8780: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==1017727==ABORTING
```

**Additional context**
Built with address sanitizer.

**Comment by hfiguiere** [comment]
It is not the first time I see this stack trace, and I still lack reproduction steps.

**Comment by leozide** [comment]
Can you get the name of the file it's trying to load?

**Comment by Symbian9** [comment]
> Can you get the name of the file it's trying to load?

Is not it defined in issue description:

> This one happen while looking for piece 24307 in the parts inventory

**Comment by hfiguiere** [comment]
After the crash I had to redo what I was doing and went through the same parts and no crash.

As I said, I don't have repro steps, but it has happened more than once. And if I remember only when selecting / find a part.

**Comment by leozide** [comment]
You said you were looking for that part, but while searching the app may be loading other parts to generate their previews and one of them could have caused the crash.

**Comment by hfiguiere** [comment]
But previous crashes I wasn't searching that part.

I'll try to reproduce.

**Comment by leozide** [comment]
I was able to get this 100% loading 6821.dat on Windows.

**Comment by hfiguiere** [comment]
thanks!
