### ISSUE TITLE
blender addon fails to load/install required files/libs

### ISSUE THREAD

**Issue by nathaneltitane** [leozide/leocad#878]
![image](https://github.com/leozide/leocad/assets/5674757/09f2fe7c-b7ba-42cb-ada5-c7c222d31732)

**Comment by nathaneltitane** [comment]
![image](https://github.com/leozide/leocad/assets/5674757/cc1fab7f-dd58-4b1b-b35f-05800d8a36ad)

**Comment by tampe125** [comment]
I'm bumping this issue since I had the same problem.  
At first the problem was with downloading the zip archive, so I manually placed it in the download folder. I moved one step forward, but there' some output from addon installation so LeoCAD complains.  
I even tried to install the addon manually inside Blender, but I can't find it in the list of Add-ons.  
I suspect something might have been changed in Blender and the addon is no longer compatible (maybe?).  

Some extra info: I'm using Blender 4.2.3 LTS, downloaded as AppImage and started it from terminal, nothing fancy.

**Comment by trevorsandy** [comment]
Hello Davide - Some questions if you don't mind...

1. What platform are you running LeoCAD on ?
2. What version of LeoCAD are you running ?
3. What version of the Blender Addon are you running ?

> At first the problem was with downloading the zip archive, so I manually placed it in the download folder.

4. What was the actual download folder - which invariably was not correct ?

> but there' some output from addon installation so LeoCAD complains.

5. Can you provide the log information for the 'complains' ?

> I even tried to install the addon manually inside Blender, but I can't find it in the list of Add-ons.

6. Can you provide some more detail on what steps you took to _manually install_ the addon ?
7. Can you say exactly where you have placed the addon links (or modules) e.g. ...blender/4.2/scripts/addons ?

Version 1.5.5 and later was tested on Blender 4.2.1 (zip distro) on Windows 11.

Cheers,

**Comment by tampe125** [comment]
Hello,  

below you can find the requested answers: 

1. Ubuntu 20.04.6 LTS
2. LeoCAD-Linux-ed29dad7-x86_64.AppImage
3. Blender 4.2.3 LTS
4. Failed to download Blender addon archive: /home/tampe125/.local/share/LeoCAD Software/LeoCAD/Blender/LDrawBlenderRenderAddons.zip . I manually created the directory path but LeoCAD still failed. I then manually downloaded the ZIP file from the repository, version 04.10.2024 and placed in that folder. LeoCAD says "Addon not configured - Update". I click on Update but nothing changes. 
5. Oddly enough, I tested again on home PC and nothing is displayed. I'll check later on my work PC since there's a different version of Ubuntu
6. If I open Blender and get in the Addon tab, I can't see anything related to LDraw/LeoCAD/LEGO in general. So I performed the manual installation by clicking on "Install from Disk". Nothing changes on the GUI, but in the console I get the message "Modules Installed () from '/tmp/LDrawBlenderRenderAddons.zip' into '/home/tampe125/.config/blender/4.2/scripts/addons'"
7. See above, I didn't manually move any file, I simply used Blender interface

**Comment by trevorsandy** [comment]
> At first the problem was with downloading the zip archive, so I manually placed it in the download folder. I moved one step forward, but there' some output from addon installation so LeoCAD complains.

The download behaviour is most likely because the AppImage build is not able to resolve required SSL paths - which produces this output on LeoCAD appimage startup:

```bash
qt.network.ssl: QSslSocket: cannot resolve EVP_PKEY_base_id
qt.network.ssl: QSslSocket: cannot resolve SSL_get_peer_certificate
qt.network.ssl: QSslSocket: cannot call unresolved function SSL_get_peer_certificate
```

> I even tried to install the addon manually inside Blender, but I can't find it in the list of Add-ons.

You must use the addon install script to perform the installation otherwise the addon will not be properly configured. This is most likely why you do not see the addon inside Blender after attempting to install the modules directly from the Blender UI.

I'm trying to replicate your environment (using WSL2) without success. LeoCAD is ok but Blender 4.2.3 immediately segfaults on launch with an `EGL Error (0x3009): EGL_BAD_MATCH: Arguments are inconsistent (for example, a valid context requires buffers not supplied by a valid surface).` error. I also tried with a Docker Ubuntu image using Xsrv and could not get Blender to start there either.

The net-net is I wasn't able to actually test the following guidance on manually installing the addon using the addon script.

The following assumes Blender and LDraw are installed at `/home/tampe125/software`, change accordingly.

1. Open and console session and set required environment variables:

```bash
export LDRAW_DIRECTORY=/home/tampe125/software/ldraw
export ADDONS_TO_LOAD=[{"load_dir":"/home/tampe125/.local/share/LeoCAD Software/LeoCAD/Blender/addons/io_scene_import_ldraw","module_name":"io_scene_import_ldraw"},{"load_dir":"/home/tampe125/.local/share/LeoCAD Software/LeoCAD/Blender/addons/io_scene_import_ldraw_mm","module_name":"io_scene_import_ldraw_mm"},{"load_dir":"/home/tampe125/.local/share/LeoCAD Software/LeoCAD/Blender/addons/io_scene_render_ldraw","module_name":"io_scene_render_ldraw"}]
```

2. Download and extract the Blender Addon

```bash
cd "/home/tampe125/.local/share/LeoCAD Software/LeoCAD/Blender/"
wget . "https://github.com/trevorsandy/blenderldrawrender/releases/download/v1.5.6/LDrawBlenderRenderAddons.zip"
unzip LDrawBlenderRenderAddons.zip
```

3. Install the addon - Enable LDraw Import MM (Disable LDraw Import TN in Blender, use `--disable_ldraw_import_mm` to Enable LDraw Import TN)

```bash
/home/tampe125/software/blender-4.2.3/blender-launcher  --background --python install_blender_ldraw_addons.py -- --leocad --disable_ldraw_import
```

If there are any problems, you can check the _stderr_ and _stdout_ logs which will be deposited at your present location.

Additionally, before launching the addon dialog in LeoCAD, review the _LDrawRendererPreferences.ini_ file in `./setup/addon_setup/config` to ensure
keys _ldrawdirectory_, _ParameterFile_, _ldrawpath_ have valid values.

Open the addon dialog in LeoCAD and confirm no errors in configuration.

Cheers,

**Comment by nathaneltitane** [comment]
follow up on this issue: the download manager now functions but the required directories in the user's home are not present prior to unpack and the unpack/installation fails.

**Comment by trevorsandy** [comment]
> follow up on this issue: the download manager now functions but the required directories in the user's home are not present prior to unpack and the unpack/installation fails.

Thank you for reporting this behaviour. Can you add a bit more information:

- What operating system are you using ?
- What 'required directories' are not present prior to unpack ?
- What is(are) the symptom(s) of the failure - was there any messages or logged information you can share ?

Cheers,

**Comment by nathaneltitane** [comment]
debian 12 64bit (KDE)
/home/nathanel/.local/share/LeoCAD Software/... (had to create manually)
message pops up in the blender add on install modal dialog that said directory is missing and that install cannot complete.

**Comment by nathaneltitane** [comment]
follow-up:

upon getting things installed (manual dir creation), this occurs:

ERROR: Exception:
 Traceback (most recent call last):
 File "/usr/lib/python3.11/shutil.py", line 825, in move
 os.rename(src, real_dst)
 PermissionError: [Errno 13] Permission denied: '/tmp/pip-target-nis4807b/lib/python/debugpy' -> '/usr/local/lib/python3.11/dist-packages/debugpy'
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
 File "/usr/lib/python3/dist-packages/pip/_internal/cli/base_command.py", line 160, in exc_logging_wrapper
 status = run_func(*args)
 ^^^^^^^^^^^^^^^
 File "/usr/lib/python3/dist-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
 return func(self, options, args)
 ^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/usr/lib/python3/dist-packages/pip/_internal/commands/install.py", line 566, in run
 self._handle_target_dir(
 File "/usr/lib/python3/dist-packages/pip/_internal/commands/install.py", line 625, in _handle_target_dir
 shutil.move(os.path.join(lib_dir, item), target_item_dir)
 File "/usr/lib/python3.11/shutil.py", line 841, in move
 copytree(src, real_dst, copy_function=copy_function,
 File "/usr/lib/python3.11/shutil.py", line 561, in copytree
 return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/usr/lib/python3.11/shutil.py", line 459, in _copytree
 os.makedirs(dst, exist_ok=dirs_exist_ok)
 File "<frozen os>", line 225, in makedirs
 PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.11/dist-packages/debugpy'
